### ISSUE TITLE
viperx: allow setting map values through env vars

### ISSUE THREAD

**Issue by zepatrik** [ory/x#137]
**Describe the bug**

We don't parse map values from environmental variables until now. Someone will come and complain about that at some point.

**Expected behavior**

I guess we should use some proper format for that, let's investigate if e.g. kubernetes defines some.

**Comment by ptescher** [comment]
I am complaining! Cant enable header mutator because `MUTATORS_HEADER_CONFIG` expects a map.

**Comment by aeneasr** [comment]
:D If you have any ideas how to fix that, it would be super helpful! Unfortunately viper is pretty...hard to work with.

**Comment by aeneasr** [comment]
This is resolved by using koanf, it is now possible to set JSON encoded values in env vars
