### ISSUE TITLE
sqlcon: traces contain argument values even if omitargs option has been set

### ISSUE THREAD

**Issue by aaslamin** [ory/x#15]
**Describe the bug**

Trace spans still contain SQL args as a tag even if omitargs option has been set 😢 

**To Reproduce**

Steps to reproduce the behaviour:

Hydra consumes this package so we can use it for manual testing. Follow https://www.ory.sh/docs/hydra/hydra-debugging#alright-how-can-i-set-this-up-locally to setup tracing and make a call to Hydra. You will notice that the sql arguments are still added as a tag even though the omitargs options has been set (by default in Hydra).

**Expected behaviour**

Trace spans should NOT contain tags for arguments if the omitargs option has been set.

**Screenshots**

See issue linked below

**Version:**

All versions

**Additional context**

This is a bug in the underlying library we use to instrument our db driver with the opentracing API. See https://github.com/luna-duclos/instrumentedsql/issues/10

## Solution

The bug [seems to have been addressed in the upstream library already](https://github.com/luna-duclos/instrumentedsql/pull/11). In order to fix:

• Bump version of https://github.com/luna-duclos/instrumentedsql to latest version
• Run unit tests to ensure everything is A-OK
• Bump patch version of github.com/ory/x and release

**Comment by aeneasr** [comment]
Sounds good, let's go ahead with that!

**Comment by aaslamin** [comment]
Closed by https://github.com/ory/x/pull/16
