### ISSUE TITLE
Cannot upgrade to latest version

### ISSUE THREAD

**Issue by mitar** [ory/x#198]
**Describe the bug**

I am trying to upgrade all fosite dependencies using `go get -u` but it fails

**To Reproduce**

```
go get -u ./...
```

**Expected behavior**

Dependencies get upgraded.

**Expected behavior**

I get the following error:

```
/home/mitar/go/pkg/mod/github.com/ory/x@v0.0.149/logrusx/helper.go:13:2: module go.opentelemetry.io/otel@latest found (v0.11.0), but does not contain package go.opentelemetry.io/otel/plugin/httptrace
```

It seems  go.opentelemetry.io/otel v0.5.0 was the latest version to contain that plugin.

**Comment by zepatrik** [comment]
They moved it in https://github.com/open-telemetry/opentelemetry-go/pull/1032 (released with v0.11.0)
But we use v0.6.0 in `go.mod` anyway, I think you should not upgrade the dependency like this. Maybe just bump the version of `ory/x` explicitly?

**Comment by aeneasr** [comment]
`go get -u` is known to always cause issues because it forcefully updates all dependencies, defeating the purpose of go modules.

**Comment by mitar** [comment]
Hm, I will have to learn how to upgrade dependencies better it seems. I was only trying to upgrade fosite and it seems it didn't respect its `go.mod`. Probably because of the bad command. Thanks.
