### ISSUE TITLE
logrusx/helper.go trace logging not working

### ISSUE THREAD

**Issue by aarmam** [ory/x#313]
**Describe the bug**
Switch from go.opentelemetry.io/otel v0.6.0 to go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace v0.13.0 breaks logging in https://github.com/ory/x/blob/master/logrusx/helper.go#L84-L93

**To Reproduce**
Request with header 
traceparent=00-b67866858ff865fb4d89725465fd2bf4-e7f3f812960b1654-01
should log "otel":{"span_id":"e7f3f812960b1654","trace_id":"b67866858ff865fb4d89725465fd2bf4"}

I tried to switch back to go.opentelemetry.io/otel v0.6.0 and then it worked.

**Comment by aeneasr** [comment]
So what could fix that?

**Comment by wangleibeckham** [comment]
This is still an issue when upgrading opentelemetry to 0.20.0 as [spanContext](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/trace.go#L205) now has only protected properties. Which makes [here](https://github.com/ory/x/blob/master/logrusx/helper.go#L90) and [here](https://github.com/ory/x/blob/master/logrusx/helper.go#L93) to break.

I can create a PR for this. @aeneasr let me know your thoughts. Thanks!
