### ISSUE TITLE
Broken Dependency Chain

### ISSUE THREAD

**Issue by DuncanES** [ory/x#742]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/x/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/x/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The most recent release of this package [v0.0.214] has a set of broken dependencies. In the go.mod file you are using github.com/gobuffalo/pop/v5(v5.3.1). This version of gobuffalo/pop has a dependency to a accidental 2.0.x release of github.com/mattn/go-sqlite3. Please update the version of gobuffalo/pop to have one that does not use a 2.0.x release of github.com/mattn/go-sqlite3 and create a new release. Please and thank you!

### Reproducing the bug

When this package is used in a go module and you try to use the command `go mod tidy` it will throw this error.

### Relevant log output

```shell
go: github.com/ory/x@v0.0.214 requires
	github.com/gobuffalo/pop/v5@v5.3.1: github.com/gobuffalo/pop/v5(v5.3.1) depends on excluded github.com/mattn/go-sqlite3(v2.0.3+incompatible) with no newer version available
```

### Relevant configuration

```yml
Go version 1.13.8
```

### Version

0.0.214

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by alnr** [comment]
Fixed AFAICT.
