### ISSUE TITLE
To support generic string in stringslice

### ISSUE THREAD

**Issue by BananZG** [ory/x#775]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/x/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/x/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The current strings and stringslice works fine with string but not custom typed 'enum' string.

### Describe your ideal solution

im using code like this locally with `~string` type constraint:

```
// Has returns true if the needle is in the haystack (case-sensitive)
func Has[T ~string](haystack []T, needle T) bool {
	for _, current := range haystack {
		if current == needle {
			return true
		}
	}
	return false
}
```

### Workarounds or alternatives

mapping list of enums into string manually first, then use original stringslice.Has

### Version

v0.0.614

### Additional Context

open to any comment regarding of using type constraint

**Comment by alnr** [comment]
Use https://pkg.go.dev/slices#Contains instead.
